# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 21:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demo_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('appointment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_port', models.CharField(max_length=50)),
                ('next_port', models.CharField(max_length=50)),
                ('appointment_type', models.CharField(max_length=50)),
                ('master_name', models.CharField(max_length=50)),
                ('voyage_no', models.CharField(max_length=50)),
                ('imo', models.CharField(max_length=50)),
                ('nominator', models.CharField(max_length=50)),
                ('charterer', models.CharField(max_length=50)),
                ('call_purpose', models.CharField(max_length=50)),
                ('my_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo_app.Port')),
                ('principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo_app.Principal')),
                ('vessel_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo_app.Vessel')),
            ],
        ),
    ]
